project:
  type: website

website:
  title: "2023_DAIE_ICA_1_FM"
  navbar:
    left:
      - href: index.qmd
        text: Index
      - href: PartA.qmd
        text: SQL

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual